### ISSUE TITLE
Update for Dragonflight?

### ISSUE THREAD

**Issue by j-mes** [ascott18/ImprovedStableFrame#2]
Hello there.

Just a quick message to mention that this still works in Dragonflight however it's listed as an out of date addon. I surmise changing the version from

```## Interface: 90002```

to 

```## Interface: 100000```

should fix the 'out of date' addon warning in-game.

**Comment by khay85** [comment]
yes, please update. I'm having tons of errors and I want to get rid of all addons that appear to be abandoned. most mods have been updated for a few weeks now for DF.

**Comment by ascott18** [comment]
@khay85 I can't help you if you don't post the "tons of errors" that you're getting. The addon seems to work perfectly fine.
