### ISSUE TITLE
Error after 10.2.7 Patch

### ISSUE THREAD

**Issue by jleafey** [ascott18/ImprovedStableFrame#7]
Since the patch released, getting an exception when logging in to any of my hunters.  Here's what I was able to retrieve via BugGrabber:

3x ...eImprovedStableFrame/ImprovedStableFrame.lua:7: attempt to perform arithmetic on global 'NUM_PET_STABLE_PAGES' (a nil value)
[string "@ImprovedStableFrame/ImprovedStableFrame.lua"]:7: in main chunk

Locals:
clientVersion = 100207
wow_900 = true
wow_800 = true
wow_503 = true
(*temporary) = nil
(*temporary) = nil
(*temporary) = ""
(*temporary) = " "
(*temporary) = " "
(*temporary) = " "
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to perform arithmetic on global 'NUM_PET_STABLE_PAGES' (a nil value)"

Thanks!

**Comment by ascott18** [comment]
The stable has been completely redesigned by blizzard. As such, this addon no longer serves a purpose (for retail).

**Comment by jleafey** [comment]
Doh! Yes, just figured that out.  Sorry to raise an alarm unnecessarily!  I loved the way the addon displayed my pets.  The new stable frame is better than it was, but not better than the add-on, IMO.  Thanks!
